version: "3"
services:
  hmpps-prisoner-cell-allocation-api:
    build:
      context: .
    network_mode: "host"
    container_name: hmpps-prisoner-cell-allocation-api
    ports:
      - "8081:8080"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health/ping"]
    environment:
      - SERVER_PORT=8080
      - SPRING_PROFILES_ACTIVE=dev

  hmpps-welcome-people-into-prison-api-db:
    image: postgres
    networks:
      - hmpps
    container_name: hmpps-prisoner-cell-allocation-api-db
    restart: always
    ports:
      - "5431:5432"
    environment:
      - POSTGRES_PASSWORD=test
      - POSTGRES_USER=test
      - POSTGRES_DB=hmpps-prisoner-cell-allocation-api-db

networks:
  hmpps:
