---
# Per environment values which override defaults in hmpps-prisoner-cell-allocation-api/values.yaml

generic-service:
  ingress:
    host: cell-allocation-api.prison.service.justice.gov.uk

  env:
    APPLICATIONINSIGHTS_CONFIGURATION_FILE: applicationinsights.json
    OAUTH_ENDPOINT_URL: "https://sign-in.hmpps.service.justice.gov.uk/auth"
    PRISON_ENDPOINT_URL: "https://prison-api.prison.service.justice.gov.uk"
